### ISSUE TITLE
error with example

### ISSUE THREAD

**Issue by cryptid11** [yangxu/google_flight_api#3]
Traceback (most recent call last):
  File "flight.py", line 30, in <module>
    g.get(data)
  File "/home/rodomonte/Desktop/google_flight_api/google_flight/google_flight_api.py", line 48, in get
    self.count = len(self.data["trips"]["tripOption"])
KeyError: 'trips'

**Comment by yangxu** [comment]
same error
check your api-key
https://console.cloud.google.com -> Go to APIs overview -> Credentials

**Comment by yangxu** [comment]
close
